name: Build Plugins

on:
  push:
    paths:
      - '.modules/**'
      - 'src/**'
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:

  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: bash ./build.sh

    - uses: actions/upload-artifact@main
      with:
        name: "RelativeModeArea"
        path: |
          ./build/RelativeModeArea.dll